services:

  # ================================================================================
  #  DATABASE
  # ================================================================================

  account-db:
    container_name: account-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: accountdb
    extends:
      file: common-config.yml
      service: common-db-config

  card-db:
    container_name: card-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: carddb
    extends:
      file: common-config.yml
      service: common-db-config

  loan-db:
    container_name: loan-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: loandb
    extends:
      file: common-config.yml
      service: common-db-config

  # ================================================================================
  #  RABBIT MQ
  # ================================================================================

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  # ================================================================================
  #  CONFIG SERVER
  # ================================================================================

  config-server:
    image: huynhducphu2502/config-server
    container_name: config-server-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  # ================================================================================
  #  SERVICES
  # ================================================================================

  account-service:
    image: huynhducphu2502/account-service
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      account-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: account-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://account-db:5432/accountdb
    extends:
      file: common-config.yml
      service: microservice-config-client

  card-service:
    image: huynhducphu2502/card-service
    container_name: card-ms
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      card-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: card-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://card-db:5432/carddb
    extends:
      file: common-config.yml
      service: microservice-config-client

  loan-service:
    image: huynhducphu2502/loan-service
    container_name: loan-ms
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      loan-db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loan-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://loan-db:5432/loandb
    extends:
      file: common-config.yml
      service: microservice-config-client

networks:
  novabank-net:
    driver: bridge