services:

  # ================================================================================
  #  SQL DATABASE
  # ================================================================================

  account-db:
    container_name: account-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: accountdb
    volumes:
      - account-data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: common-db-config

  card-db:
    container_name: card-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: carddb
    volumes:
      - card-data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: common-db-config

  loan-db:
    container_name: loan-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: loandb
    volumes:
      - loan-data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: common-db-config

  # ================================================================================
  #  Redis
  # ================================================================================

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin123
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "admin123", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 300m
    extends:
      file: common-config.yml
      service: network-deploy-service


  # ================================================================================
  #  RABBIT MQ
  # ================================================================================

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  # ================================================================================
  #  CONFIG SERVER
  # ================================================================================

  infra-server:
    image: huynhducphu2502/infra-server
    container_name: infra-server-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    environment:
      SPRING_APPLICATION_NAME: infra-server
    extends:
      file: common-config.yml
      service: microservice-base-config

  # ================================================================================
  #  SERVICES
  # ================================================================================

  account-service:
    image: huynhducphu2502/account-service
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      account-db:
        condition: service_healthy
      infra-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: account-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://account-db:5432/accountdb
    extends:
      file: common-config.yml
      service: microservice-config-client

  card-service:
    image: huynhducphu2502/card-service
    container_name: card-ms
    ports:
      - "8081:8081"
    depends_on:
      card-db:
        condition: service_healthy
      infra-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: card-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://card-db:5432/carddb
    extends:
      file: common-config.yml
      service: microservice-config-client

  loan-service:
    image: huynhducphu2502/loan-service
    container_name: loan-ms
    ports:
      - "8082:8082"
    depends_on:
      loan-db:
        condition: service_healthy
      infra-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: loan-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://loan-db:5432/loandb
    extends:
      file: common-config.yml
      service: microservice-config-client

  # ================================================================================
  #  GATEWAY SERVER
  # ================================================================================

  gateway-server:
    image: huynhducphu2502/gateway-server
    container_name: gateway-server-ms
    ports:
      - "8765:8765"
    depends_on:
      account-service:
        condition: service_healthy
      card-service:
        condition: service_healthy
      loan-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: gateway-server
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: admin123
    extends:
      file: common-config.yml
      service: microservice-config-client


networks:
  novabank-net:
    driver: bridge