services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: huynhducphu2502/config-server
    container_name: config-server-ms
    ports:
      - "8701:8701"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8701/actuator/health/readiness | grep UP || exit 1"
      start_period: 10s
      retries: 10
      timeout: 5s
      interval: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  account-service:
    image: huynhducphu2502/account-service
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: account-service
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card-service:
    image: huynhducphu2502/card-service
    container_name: card-ms
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: card-service
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan-service:
    image: huynhducphu2502/loan-service
    container_name: loan-ms
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loan-service
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  novabank-net:
    driver: bridge